### ISSUE TITLE
When would xsimd has next new Release?

### ISSUE THREAD

**Issue by mapleFU** [xtensor-stack/xsimd#1015]
Apache Arrow now use xsimd 9.0.1 by default [1]. I'd like to shifting it to latest version. However, since master code contains some bugfixes [2][3], and arrow uses xsimd when neon64 enabled, I'd like to change to latest version when new release is enabled.

So may I ask when would xsimd has next new release? Thanks!

[1] https://github.com/apache/arrow/blob/23bece4e4840758795f12db75ec919f91f21f006/ci/conan/all/conanfile.py#L227
[2] https://github.com/xtensor-stack/xsimd/commit/836b4c359edbb34e4c4448cccd9bb4fee5e34c89
[3] https://github.com/xtensor-stack/xsimd/commit/1d8536b393171b899031f01b7c2d63858b05665c

**Comment by serge-sans-paille** [comment]
We planned a major release once #1009 is fixed. We could do an intermediate release in between, but I think current master branch already contains some minor API breakage, so that still would be a major version change.
After some thoughts it's probably better to let some time live between two major release, so I'll prepare a release this week.

**Comment by mapleFU** [comment]
Thanks!

**Comment by serge-sans-paille** [comment]
See https://github.com/xtensor-stack/xsimd/pull/1019 for an intermediate (but still API-breaking) version that doesn't fix #1009 but should include the commits you mention.

**Comment by mapleFU** [comment]
Thanks!
