### ISSUE TITLE
Please add conan support for this awesome library

### ISSUE THREAD

**Issue by seertaak** [xtensor-stack/xsimd#276]
Hi, while I'm aware that you provide packaged support for `conda`, which is great, as a C++ dev it would make it much easier to use *xsimd* if the library had support for conan. My understanding is that it's very easy (one extra file) to provide this support, especially so for a header-only package. Moreover, the conan team have in my own interactions been very positive -- I'm sure they'll be happy to guide you through the process.

Thanks for your effort in creating such a great library, by the way.

**Comment by wolfv** [comment]
would you be interested in adding the support? that would be a great, small + quick PR :)

**Comment by tdegeus** [comment]
Based on this comment I've been Googling a bit for conan. It too seems quite nice. Am I correct that its major advantage is architecture independent packaging for header-only libraries?

Indeed a PR would be great! I'd be happy to help, but since you, @seertaak, seem to have experience with conan, it would be great if you find a chance to make a start.

**Comment by seertaak** [comment]
Hi - apologies for the late reply. Before yesterday I actually wrote the `conanfile.py` and it worked on my system. Nothing fancy; I didn't bother about the tests, I just followed their instructions for header-only libraries.

However, I didn't manage to create a PR. I'm off to Berlin until Sunday so it won't be until Monday evening that I get the change to submit it.

**Comment by tdegeus** [comment]
Great! 

(Obviously no worries, your reply is still quiet fast!)

**Comment by omaralvarez** [comment]
If there are any problems I can help @seertaak , I also want to use it with conan and have experience creating conan packages.

**Comment by wolfv** [comment]
If @seertaak hasn't started to push this to some conan repository, i think it's fine if you take the initiative here @omaralvarez.

**Comment by omaralvarez** [comment]
I have made a simple version on a separate repo so that Conan packaging is not mixed with the lib code. Easier to maintain for me, but please let me know if you prefer integrating it in the xsimd repo.

https://github.com/omaralvarez/conan-xsimd

Working on a readme right now.

I could add a pull request of your README.md to add instructions on how to use Conan.

**Comment by JohanMabille** [comment]
@omaralvarez Awesome! Keeping the code for packaging in dedicated repos is indeed better than mixing it with the lib code, that's already what we do for conda packages.

We are definitely interested in a PR to update the README with instructions for Conan installations (and a link to your repo ;)).

**Comment by omaralvarez** [comment]
@JohanMabille Done! #288

**Comment by JohanMabille** [comment]
Closing now that the support for Conan has been implmeented i a dedicated repo.
