### ISSUE TITLE
batch_bool comments

### ISSUE THREAD

**Issue by ojwoodford** [xtensor-stack/xsimd#309]
Hi

I'm using the types `batch<float, 4>` and `batch<int32_t, 4>` on an intel system, and have various issues casting to/from batch_bool.
- `batch_bool<int32_t, 4> inBounds = (x >= 0) & (y >= 0) & (x <= width) & (y <= height);` does not compile. I need to use `batch_bool<int32_t, 4> inBounds = (0 <= x) & (0 <= y) & (x <= width) & (y <= height);`
- `bitwise_cast(inBounds)` produces -1 instead of 1 for true.

**Comment by JohanMabille** [comment]
Hi,

Thanks for reporting!

#310 fixes thecomparison issue.
Regarding `bitwise_cast`, it is the expected behavior. Binary representation of boolean can be arbitrary as long as `true` can be converted to `1` and `false` can be converted to `0`. The `bitwise_cast` function does not perform such a conversion, it is a "reinterpretation" of the binary representation into another type.

However, `xsimd` does not provide any mean to convert a `batch_bool`holding true to a `batch` holding `1`, that's something we definitely need to fix.
