### ISSUE TITLE
About adding new features

### ISSUE THREAD

**Issue by cyb70289** [xtensor-stack/xsimd#412]
Hi,

Thanks for creating xsimd which is a cool simd wrapper.

Current implementation looks focusing on basic data load/store and math operations, without advanced features like shuffle, zip, saturated op, etc. I wonder if contribution is welcomed to adding new features to xsimd lib.

In issue #375, @JohanMabille mentioned `combinatory issue` makes it hard to implement `shuffle` feature. I haven't dig deep the source code. Would be great is someone can explain what the issue is, and if we can improve it. Thanks.

Yibo

**Comment by pitrou** [comment]
Also, for the sake of comparison, here is [libsimdpp's array of shuffling operations](https://p12tic.github.io/libsimdpp/v2.2-dev/libsimdpp/w/shuffle.html). In the context of Apache Arrow, at least `zip_lo` and `zip_hi` would be useful AFAICT. Arrow contributors can certainly contribute them if necessary :-)

**Comment by JohanMabille** [comment]
> Current implementation looks focusing on basic data load/store and math operations, without advanced features like shuffle, zip, saturated op, etc. I wonder if contribution is welcomed to adding new features to xsimd lib.

Any contribution is definitely welcome! There are a lot of things missing in xsimd that we like to have, we just miss the ressources to implement them quickly. So we usually wait for demand to implement them when we can, or even better for contributions.

Regarding the combinatory issue, the idea we had in mind was to implement something like (_builtin_shufflevector)[https://clang.llvm.org/docs/LanguageExtensions.html#langext-builtin-shufflevector] from clang. In that case, we would have to provide a kernel for each possible permutation (if we want to use the most efficient combination of available intrinscs), thus the combinatory issue. Buth maybe htere is a way to have some generic implementation that would be acceptable for almost all the cases.

**Comment by pitrou** [comment]
@edponce I don't know if this is something you have an opinion on/could help with?

Note: the context for Arrow is https://github.com/apache/arrow/pull/9424, we don't need the full flexibility of generic shuffle.

**Comment by edponce** [comment]
Hi all,

When working with vector operations, I have come across the combinatory issue in _shuffle/permute/shift_ operations and it does presents its share of challenges. It is not trivial to find a good balance between a clean API, generality, and performance. SIMD libraries tend to have a targeted focus b/c they are usually driven by operations of interest (and this is fine).

[_builtin_shufflevector](https://clang.llvm.org/docs/LanguageExtensions.html#langext-builtin-shufflevector) and [libsimdpp](https://p12tic.github.io/libsimdpp/v2.2-dev/libsimdpp/w/shuffle.html) offer different API approaches for generality.
* _builtin_shufflevector uses variable parameters to dictate the operations. Given that vector ISAs vary in width this will require multiple versions of the client code.
* libsimdpp exposes the different operations via different functions
* An alternative approach is to use [enumerated types](https://github.com/edponce/libsimdcpp/blob/master/include/sse4_2.h#L46) as parameters to specify the operations and have a [_switch_ statement handle the different cases](https://github.com/edponce/libsimdcpp/blob/master/include/sse4_2.h#L1400).

I am not arguing which approach is best for generality as it will depend but I think it is worthwhile to consider different solutions and APIs.

Also, to comment on this thread's main topic, I am open to contribute to xsimd in order to provide better support for Arrow and related projects.

**Comment by serge-sans-paille** [comment]
I'll give a try to zip_lo / zip_hi and report here!

**Comment by guyuqi** [comment]
Thanks for your interest. @serge-sans-paille 
As discussed in https://github.com/apache/arrow/pull/9424, I'm working on add zip_lo / zip_hi (both x86 and Arm64)to xsimd and will submit th PR soon and wil fix build issues on Arm64 when `-DBUILD_TESTS=ON`.

**Comment by serge-sans-paille** [comment]
ok, thanks @guyuqi for letting me know. I won't interfere on that part then :-)
What about the `lrot` and `rrot` operations that perform a rotation on the left / right ?

**Comment by JohanMabille** [comment]
Thanks @edponce for sharing your experience on this. Giving that we are many developers interested in adding the shuffle functinos, I think a good approach for `xsimd` could be to implement the different shuffle operations into dedicated functions, similar to libsimdpp. This will allow us to work in parallel and make quick progress on what we need now instead of waiting for having a whole implementation.

We can add a generic dispatch later (when we have implemented enough functions so that it make sense to have it), either with an API similar to the builtins, or with enumerated types + switch as suggested by @edponce.

Notice that this does not prevent us from providing the builtin function when it is available (as we do for `prefetch` for instance).

**Comment by JohanMabille** [comment]
I'm going to open issues for functions that are currently under developement (and assign them to the developers working on it), please do not hesitate to open more and ping me to assign them if you want to implement other functions. This will avoid to duplicate the work.
