### ISSUE TITLE
Why not let the compiler for SIMD opt for you?

### ISSUE THREAD

**Issue by jingchangshi** [xtensor-stack/xsimd#486]
Will using this library to do SIMD give me a lot of performance gain over the compiler's optimization? I know the fundamentals of SIMD and the articles on the Intel compiler webpage guide me how to design the data layout for SIMD.
The work done by this library seems to be the job done by the compiler including Intel, gcc, clang.

**Comment by serge-sans-paille** [comment]
For simple kernels, xsimd and compilers are on par. But for more complex ones, like those involving trigonometric functions, performance may vary across compilers, while xsimd guarantees performance across architectures and compilers. See for instance https://godbolt.org/z/vEn4WsrvT that gcc cannot vectorize (but icc can).

**Comment by jingchangshi** [comment]
> For simple kernels, xsimd and compilers are on par. But for more complex ones, like those involving trigonometric functions, performance may vary across compilers, while xsimd guarantees performance across architectures and compilers. See for instance https://godbolt.org/z/vEn4WsrvT that gcc cannot vectorize (but icc can).

Thanks for the reply! This makes sense and is helpful!
My in-house high order CFD code runs much faster if compiled by Intel than that by gcc. Maybe I should use xsimd for the gcc branch.
I feel it would be better to put this explanation in README of this repo.

**Comment by namniav** [comment]
> See for instance https://godbolt.org/z/vEn4WsrvT that gcc cannot vectorize (but icc can).

@serge-sans-paille  For this instance, GCC can vectorize it if you allow [`-ffast-math`](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Optimize-Options.html#index-ffast-math), see https://godbolt.org/z/T39eaPf5q. GCC can't vectorize it without `-ffast-math` because vectorization possibly would not give accuract IEEE or ISO results.

@jingchangshi 
IMO it's hard, especially for beginers like me, to get better performance by writing *general* simd code or xsimd code than modern compiler's auto-vectorization, eg. https://github.com/xtensor-stack/xsimd/issues/381. 
Most of the time, a benchmark will be helpful.
