### ISSUE TITLE
single value batch initialisation failing for double on avx

### ISSUE THREAD

**Issue by prateekgargX** [xtensor-stack/xsimd#775]
![Screenshot (133)](https://user-images.githubusercontent.com/84305275/174828661-3337dad8-3a41-4015-b86c-694dc4388d1f.png)

It initializes the first value with all other garbage. The broadcast is failing.
https://xsimd.readthedocs.io/en/latest/api/xsimd_batch.html#_CPPv4N5xsimd5batch5batchE1T

**Comment by wermos** [comment]
If you look at `include/xsimd/types/xsimd_batch.hpp`, you'll find the following constructor definitions:
![image](https://user-images.githubusercontent.com/63574588/174852475-5171e0a5-39a3-4728-934d-3e5922a371d0.png)

It looks like the line `xsimd::batch<double, xsimd::avx2> c{2.5};` is calling the second overload, because it treats the `{2.5}` as an initializer list.

I am not sure if this is the intended behavior, though.

**Comment by serge-sans-paille** [comment]
> since xsimd gives you compilation errors when you try to compile in Debug mode (unless you pass in the explicit ISA flags, which vary from compiler to compiler)

I'm interested in the details here.

**Comment by serge-sans-paille** [comment]
> The message, "consistent initialization" isn't a very illuminating one.

Agreed.

**Comment by serge-sans-paille** [comment]
An alternative to the solution you're providing is to *not* define an initializer_list constructor, and instead provide 

```
batch(std::array<T, size> data) noexcept;
```
This would remove the inconsistency, at the expense of refusing the syntax

```
batch<int> b = {1,2,3,4};
```

while still allowing

```
batch<int>b({1,2,3,4})
```

Any thoughts on that one?

**Comment by wermos** [comment]
> Any thoughts on that one?
While it indeed works as expected, the only down sides I can think of are (a) an API change (which might affect other users?) and (b) the loss of the `= {...}` syntax. Maybe we can mitigate the second one by providing a custom [copy-assignment operator](https://en.cppreference.com/w/cpp/language/copy_assignment)?

**Comment by wermos** [comment]
Also, the example delegating constructor code I gave is slightly wrong, but I managed to make it work. The only problem is that it is a little bit unsightly, so it should be properly commented:
```cpp
template <class T, class A>
inline batch<T, A>::batch(T val) noexcept
    : types::simd_register<T, A>(kernel::broadcast<A>(val, A {}))
{
 } // this constructor stays the same

template <class T, class A>
inline batch<T, A>::batch(std::initializer_list<T> data) noexcept // delegating constructor call below
: batch((data.size() == 1) ? batch(*data.begin()) : batch(data.begin(), detail::make_index_sequence<size>()))
// the idea is that if the length of `data` is 1, then call the broadcasting constructor, else do what was being
// done before; this essentially the copy constructor after the ternary operator is evaluated
{
    if (data.size() != 1) {
        details::check_batch_init(*this, data);
    }
}
```
Motivated by [this SO answer](https://stackoverflow.com/a/29173237/12591388).

**Comment by serge-sans-paille** [comment]
@marzer : I'm pretty confident the branching is removed by the compiler, that's not something that worries me. The syntax you propose would require a variadic template constructor but that's probably better. Let me investigate that one!

**Comment by marzer** [comment]
> The syntax you propose would require a variadic template constructor but that's probably better. Let me investigate that one!

It wouldn't if you use SFINAE. It also allows conversion between the inputs to the batch's `T` type to work, whereas using a variadic template would disable that behaviour.

**Comment by marzer** [comment]
To wit:

```cpp
batch(T val) noexcept
{
	// ...
}

, 

template <size_t S = batch::size, typename std::enable_if<S == 2, int>::type = 0>
batch(T val1, T val2) noexcept
{
	// ...
}

template <size_t S = batch::size, typename std::enable_if<S == 4, long>::type = 0>
batch(T val1, T val2, T val3, T val4) noexcept
{
	// ...
}

template <size_t S = batch::size, typename std::enable_if<S == 8, long long>::type = 0>
batch(T val1, T val2, T val3, T val4, T val5, T val6, T val7, T val8) noexcept
{
	// ...
}
```

**Comment by marzer** [comment]
@prateekgargX 

> doesn't this incur a lot of redundancy in the code? 

Welcome to C++ library development. Ever taken a look into an STL implementation? It's redundancy and repetition all the way down. At the library level is precisely where this sort of approach is appropriate - _so that users don't need to do it_.

> Also, it kills the purpose of the batch- to provide an abstraction over SIMD registers. 

It doesn't kill anything. It would still be an abstraction provided by the library - from a user perspective it looks exactly the same (except it works properly with any type of bracket).

In my example above only one of those constructors would actually be instantiated (by virtue of the SFINAE), and the `initializer_list` constructor would be deleted, so the net number of constructors per `batch` instantiation would remain unchanged.

> but in the method you suggested, will have to create a new constructor for batch.

Yup. See above. Repetition is often necessary in C++ library development. Not a huge deal here, since the number of distinct batch sizes is finite and small; You'd need a constructor for what, 2, 4, 8, 16, 32? Not hard to create manual implementations of those; they only need to be done once and they're correct forever.

Of course if @serge-sans-paille decides to go with the variadic template approach, that's fine too, it just disables implicit conversions which may not be desired.

> the method @wermos suggested would work fine

No, it has obvious consequences for debug builds. Consequences that can be completely eliminated those just by doing a little bit more work at the library level and letting the compiler do the rest.

**Comment by serge-sans-paille** [comment]
@marzer: I recognize the interest of the approach you propose, and it's indeed much better than a variadic template approach (I tried it and I ended up with subtle problems of multiple possible conversions, so I gave up that path).

That being said, from a documentation and API point of view, having multiple overloads that are selected based on SFINAE is not the cleanest and easier to understand for the user. To correctly support avx512, we would need a constructor for 2,4,8,16, 32 and 64 elements... Compared to a single `std::initializer_list` constructor. 

For the sake of simplicity, ``std::initializer_list`` is a good choice : it's one constructor, its usage is clear and easy to document. It's less fool-proof because we can't check its size at compile time though...

I 100% agree that initializer list syntax is a pain and the rules to determine which constructor is called under which circumstance are complex, but I also am not a big fan of the multiple overloads for the sake of clarity.

Once I've done some testing with modern compilers and I'm sure there's no overhead with the initialize-or-broadcast approach, I'm weighting toward that approach which looks like a good compromise. I'd be happy to read @JohanMabille opinion on this though.

**Comment by serge-sans-paille** [comment]
@marzer https://godbolt.org/z/xTjnjv1d1

**Comment by marzer** [comment]
well yeah, you're using an explicit initializer list in that example. The whole point of the exercise was to get rid of that: https://godbolt.org/z/M8GMdxcan

**Comment by marzer** [comment]
Or is that implicit batch-bool construction actually desired there? If so, then yeah, that's just asking for trouble O_o

**Comment by serge-sans-paille** [comment]
yeah, but if the user were to write this, he would end up with that very confusing message, that's something I'd like to put in the balance too.

Setting `batch(batch_bool<T, N>);` to explicit doesn't help, setting one of the other two does work but then it also prevents writing `batch<int> x = {1,2,3,4};` so I don't think that's desirable.

As a summary: initializer lists are appealing to the eye but a real pain to setup properly in all cases :-/

**Comment by marzer** [comment]
>Setting batch(batch_bool<T, N>); to explicit doesn't help 

what about making `batch_bool(...)` `explicit`?

**Comment by wermos** [comment]
>> since xsimd gives you compilation errors when you try to compile in Debug mode (unless you pass in the explicit ISA flags, which vary from compiler to compiler)
>
> I'm interested in the details here.

Here is a [short godbolt example](https://www.godbolt.org/z/znG9cW5ac). If you pass in the `-mavx` flag, then GCC successfuly compiles the code. It would be nice to have the auto-detection of the available architectures in the `CMakeLists.txt` file, because then we could easily run programs in Debug mode. In fact, Krita, one of the downstream projects which gives users the option to use xsimd for a performance boost, has a [bunch of CMake macros](https://github.com/KDE/krita/blob/0b2462cba76b62439df8913ff67a9a26b650c634/cmake/modules/xsimd/xsimdMacros.cmake) to simplify the use of xsimd with CMake.

It might be worth looking into whether those macros can be incorporated upstream, into xsimd itself.

> In release builds. Debug build performance should be a consideration, too.

I agree that debug build performance should be a consideration, but have you benchmarked the branching code and noticed any significant performance drop?

> That being said, from a documentation and API point of view, having multiple overloads that are selected based on SFINAE is not the cleanest and easier to understand for the user. To correctly support avx512, we would need a constructor for 2,4,8,16, 32 and 64 elements... Compared to a single `std::initializer_list` constructor.
>
> For the sake of simplicity, `std::initializer_list` is a good choice : it's one constructor, its usage is clear and easy to document. It's less fool-proof because we can't check its size at compile time though...

I wholeheartedly agree with the documentation thing.

However, I also agree with @marzer that `assert()`-based diagnostics are brittle. But if we were using C++14, we could actually simply do a `static_assert` because the [`.size()` member function for `std::initializer_list` is marked `constexpr` from C++14 onwards](https://en.cppreference.com/w/cpp/utility/initializer_list/size). (Moreover, another advantage would be the fact that we wouldn't have to roll our own `make_index_sequence` anymore.) This might be another reason to look towards maybe upgrading xsimd to C++14 🤔

**Comment by marzer** [comment]
> I agree that debug build performance should be a consideration, but have you benchmarked the branching code and noticed any significant performance drop?

Not this particular code example, no, but it's a 'death by a thousand cuts' problem. Too often codebases completely ignore debug performance implications in lots of small ways and end up being their own worst enemy - eventually there's just a lot of unnecessary slowness during debugging and general dev iteration. "It's OK, the optimizer will fix it" should never be the primary decision driver for codebase, IMO. When faced with two solutions to a problem, one that is entirely resolved at compile time, and one that requires runtime work, choosing the latter is one of those decision points.

I know, I know, "premature optimization is the root of all evil". It is important to consider debug performance all the same, though; if people are dissuaded from ever using debug builds, then all those `assert()` statements ultimately accomplish nothing.

> we could actually simply do a static_assert because the [.size() member function for std::initializer_list is marked constexpr from C++14 onwards](https://en.cppreference.com/w/cpp/utility/initializer_list/size).

This won't work in runtime-evaluated contexts; it only works in the example given on cppreference because the static-assert is a constant-evaluated context. If you tried that in a non-constexpr xsimd batch constructor at runtime it would fail: https://godbolt.org/z/WTMhjcPsM

**Comment by wermos** [comment]
>> I agree that debug build performance should be a consideration, but have you benchmarked the branching code and noticed any significant performance drop?
>
> Not this particular code example, no, but it's a 'death by a thousand cuts' problem.

I took the liberty of putting `std::cout` statements in the `batch` constructor code, like so:
```cpp
/**
 * Create a batch with all element initialized to \c val.
 */
template <class T, class A>
inline batch<T, A>::batch(T val) noexcept
    : types::simd_register<T, A>(kernel::broadcast<A>(val, A {}))
{
    std::cout << "broadcasting constructor\n";
}

/**
 * Create a batch with elements initialized from \c data.
 * It is an error to have `data.size() != size.
 */
template <class T, class A>
inline batch<T, A>::batch(std::initializer_list<T> data) noexcept
    : batch(data.begin(), detail::make_index_sequence<size>())
{
    details::check_batch_init(*this, data);
    std::cout << "intializer list constructor\n";
}
```
(I am using the `master` branch currently, so I had to comment out the assert statement to get the code to not segfault in debug mode.)

And then ran a little test program:
```cpp
#include <iostream>
#include <xsimd/xsimd.hpp>

int main() {
    xsimd::batch<double, xsimd::avx2> b(2.5);
    std::cout << "==========================\n";
    xsimd::batch<double, xsimd::avx2> c{2.5, 5, 7.5, 10};
    std::cout << "==========================\n";
    xsimd::batch<double, xsimd::avx2> d = {3.5, 7, 10.5, 14};
}
```
And this was the output:
```
register_type constructor
broadcasting constructor
==========================
register_type constructor
pointer-to-data constructor
intializer list constructor
==========================
register_type constructor
pointer-to-data constructor
intializer list constructor
```
There is a lot of constructor calls being done implicitly already, as-is. Point is, plenty of extra work is being done already, so I don't think a little more will affect performance too much.

> I know, I know, "premature optimization is the root of all evil". It is important to consider debug performance all the same, though

While I agree with the sentiment, I don't think that the codebase really adheres to the idea of "use compile-time options whenever they are available, for maximum performance":
For example, [this switch-case decision](https://github.com/xtensor-stack/xsimd/blob/c2728632bdfecf1dfc004e7ef9ee908003169948/include/xsimd/arch/xsimd_sse2.hpp#L52) can be taken at compile-time, using `std::enable_if`:
![image](https://user-images.githubusercontent.com/63574588/175385029-e0bee58a-e976-4953-8da7-2b49d4c2aae3.png)

There are many such instances throughout the codebase.

Ultimately, I think that you have a good point (debug performance matters!), in that we should continue with the delegating constructor approach for now, and you should open another issue regarding debug performance and we can start to tackle these issues one by one, over there.

>This won't work in runtime-evaluated contexts; it only works in the example given on cppreference because the `initializer_list` is instantiated within the `static_assert`, thus is entirely within a constant-evaluated context. If you tried that in an xsimd batch constructor at runtime it would fail: https://godbolt.org/z/WTMhjcPsM

You're right, that was my bad.

> If the documentation concerns were really so simple, and the single init list ctor was such a slam-dunk, the OP would not have made the mistake they made.

I don't think anyone here is claiming that the code, in its previous form, was fine. On the contrary, we identified a big pitfall, and that's why we are discussing about possible solutions to mitigate this issue 😄

>  I have no interest in dying on any hills here

Seconded. In my projects, I am either the one personally responsible for any code interfacing xsimd, or directly overseeing any code which interfaces xsimd, so it wouldn't make a big difference to me either way.

Cheers!

**Comment by serge-sans-paille** [comment]
An alternate implementation based on variadic template lives there: https://github.com/xtensor-stack/xsimd/tree/fix/dispatching-initializer-list-alternate
It has plenty of good properties (compile-time size checking, allows `batch a{1}`, `batch a{1,2,3,4}` and  `batch a = {1,2,3,4}`)
*but* it silently fails for  `batch a { {1,2,3,4} }` because it converts ` {1,2,3,4} ` into `batch_bool`, which worries me (I don't like that syntax, but the fact that it gets accepted is a problem)
It does not accept `batch b({1,2,3,4})` because it's ambiguous, and I'm fine with that.

**Comment by marzer** [comment]
@serge-sans-paille not sure if it would have the same problem, not at a PC to check. Will be happy to check tomorrow.

I don't actually think that's much of a problem though, is it? That's not a normal init list construction, the nesting makes it pretty clear something else is happening.

You could also get around it by making the batch bool constructor explicit.
